### ISSUE TITLE
RNGroup:getHighestLevel() crashes on math.max(unpack(self.levels)) sometimes

### ISSUE THREAD

**Issue by BlueByLiquid** [ymobe/rapanui#53] opened 2012-09-03 06:49 UTC
I seem to have resolved the problem which attempting to debug it. I changed the above code to:

function RNGroup:getHighestLevel()
    local temp = unpack(self.levels)
    return math.max(temp)
end

**Comment by MattiaFortunati** [comment] 2012-09-03 08:00
Thanks, 
I'll change this asap :D

**Comment by MattiaFortunati** [comment] 2012-09-03 15:53
Ok, I've fixed this in rapanuidev branch. I'll close the issue once everything will be merged on master.

**Comment by MattiaFortunati** [comment] 2012-09-03 16:07
Oh, I'm sorry.
I had to roll-back to previous code.
The code you gave me did not work well and made my tests crash several times.
Also, I cannot reproduce your bug. It never occurs to me.

Can you tell me how to reproduce it?

Thanks.

**Comment by BlueByLiquid** [comment] 2012-09-03 21:18
I am not an expert in lua(far far far from it) but shouldn't those two lines be the same? I was surprised that it resolved my issue for me and as I mentioned I just added it to two lines so I could debug it easier.

Anyway it oddly happens even if I do not have a group. It happens on the call to RNFactory.createImage("TestImage"). If I call that multiple times with the same image and save it in different objects it will crash at RNGroup:getHighestLevel().

Note: It happens everytime on my fifth call to RNFactory.createImage("TestImage"). with the same object but there are many other objects loaded multiple times earlier (more than 5 copies).

Maybe it is my fault for calling create image with the same image? I thought RapaNui would cache those as the same texture if they are the same file but maybe I should do it another way.

**Comment by MattiaFortunati** [comment] 2012-09-04 08:09
> I am not an expert in lua(far far far from it) but shouldn't those two lines be the same? I was surprised that it resolved my issue for me and as I mentioned I just added it to two lines so I could debug it easier.

Yes, I agree with you, those lines should be the same, but instead they broke my projects...

> Anyway it oddly happens even if I do not have a group. It happens on the call to RNFactory.createImage("TestImage"). If I call that multiple times with the same image and save it in different objects it will crash at RNGroup:getHighestLevel().
> 
> Note: It happens everytime on my fifth call to RNFactory.createImage("TestImage"). with the same object but there are many other objects loaded multiple times earlier (more than 5 copies).

I'm still not able to reproduce the bug, I've created more than 300 images and objects all in the same code and nothing happened. Can you send me a piece of code reproducing the error? 
Maybe there's something else not working properly, like physics :D

> Maybe it is my fault for calling create image with the same image? I thought RapaNui would cache those as the same texture if they are the same file but maybe I should do it another way.

Well, in my projects I can successfully create/remove dynamically a lot of images and they are cached so I don't thinks this could be the problem, but I cannot say until I cannot reproduce the bug.

Thanks. :D

**Comment by BlueByLiquid** [comment] 2012-09-04 15:27
I will try to put together a smaller demo that causes it to happen. I am using shapes (rectangle) to represent a rope and you mentioned a problem with them so maybe that is part of the problem.

**Comment by MattiaFortunati** [comment] 2012-09-04 15:30
Great!
And if you are using shapes... yes, this could be the problem because as you already know we left them behind during development.
:D

**Closed as completed** 2012-09-07 16:13 UTC
Labels: bug

**Comment by MattiaFortunati** [comment] 2012-09-14 16:28
Hey,

I could reproduce this bug. Wow, it was hard. 
I've fixed this again, I had to rewrite the "max" and "min" functions.

;D

**Comment by BlueByLiquid** [comment] 2012-09-14 20:45
I am glad you could repoduce it. I had a really difficult time trying to reproduce it in a scaled down version.

Also thanks for the fix.
